In [1]:
import pandas as pd
import numpy as np

## Section A — Easy (15 Questions)

### 1. Create `student_df` with Name, Age, and City for four students.

In [2]:
student_data = {
    'Name': ['Aarav', 'Priya', 'Kabir', 'Sara'],
    'Age': [19, 20, 18, 19],
    'City': ['Agra', 'Delhi', 'Mathura', 'Jaipur']
}
student_df = pd.DataFrame(student_data)
student_df

    Name  Age     City
0  Aarav   19     Agra
1  Priya   20    Delhi
2  Kabir   18  Mathura
3   Sara   19   Jaipur

### 2. Display the complete `student_df` DataFrame.

In [3]:
student_df

    Name  Age     City
0  Aarav   19     Agra
1  Priya   20    Delhi
2  Kabir   18  Mathura
3   Sara   19   Jaipur

### 3. Display the column names of `student_df`.

In [4]:
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

### 4. Retrieve the Name column from `student_df`.

In [5]:
student_df['Name']

0    Aarav
1    Priya
2    Kabir
3     Sara
Name: Name, dtype: object

### 5. Retrieve the City column using square-bracket notation.

In [6]:
student_df['City']

0       Agra
1      Delhi
2    Mathura
3     Jaipur
Name: City, dtype: object

### 6. Create a DataFrame containing only Name and City.

In [7]:
student_name_city = student_df[['Name', 'City']]
student_name_city

    Name     City
0  Aarav     Agra
1  Priya    Delhi
2  Kabir  Mathura
3   Sara   Jaipur

### 7. Create `book_df` from equal-length lists.

In [8]:
book_data = {
    'Book': ['Python Basics', 'Data Science 101', 'Learn Pandas'],
    'Author': ['A. Sharma', 'R. Verma', 'N. Khan'],
    'Price': [350, 500, 420]
}
book_df = pd.DataFrame(book_data)
book_df

               Book     Author  Price
0     Python Basics  A. Sharma    350
1  Data Science 101   R. Verma    500
2      Learn Pandas    N. Khan    420

### 8. Add a Publisher column with the same publisher for every row.

In [9]:
book_df['Publisher'] = 'ABC Publications'
book_df

               Book     Author  Price         Publisher
0     Python Basics  A. Sharma    350  ABC Publications
1  Data Science 101   R. Verma    500  ABC Publications
2      Learn Pandas    N. Khan    420  ABC Publications

### 9. Create a five-row DataFrame and assign `np.arange(5)` to SerialNo.

In [10]:
serial_df = pd.DataFrame({'Item': ['A', 'B', 'C', 'D', 'E']})
serial_df['SerialNo'] = np.arange(5)
serial_df

  Item  SerialNo
0    A         0
1    B         1
2    C         2
3    D         3
4    E         4

### 10. Delete SerialNo from the DataFrame created in Question 9.

In [11]:
del serial_df['SerialNo']
serial_df

  Item
0    A
1    B
2    C
3    D
4    E

### 11. Create `movie_df` with Movie, Year, and Rating.

In [12]:
movie_df = pd.DataFrame({
    'Movie': ['Dangal', '3 Idiots', 'Lagaan'],
    'Year': [2016, 2009, 2001],
    'Rating': [8.3, 8.4, 8.1]
})
movie_df

      Movie  Year  Rating
0    Dangal  2016     8.3
1  3 Idiots  2009     8.4
2    Lagaan  2001     8.1

### 12. Request Movie, Rating, and a Director column not in the original.

In [13]:
movie_selected = movie_df.reindex(columns=['Movie', 'Rating', 'Director'])
movie_selected

      Movie  Rating  Director
0    Dangal     8.3       NaN
1  3 Idiots     8.4       NaN
2    Lagaan     8.1       NaN

### 13. Create a Series with city names at indexes 0 and 3.

In [14]:
city_series = pd.Series(['Agra', 'Delhi'], index=[0, 3])
city_series

0     Agra
3    Delhi
dtype: object

### 14. Assign that Series to Branch in a four-row DataFrame.

In [15]:
branch_df = pd.DataFrame({'Student': ['A', 'B', 'C', 'D']})
branch_df['Branch'] = city_series
branch_df

  Student Branch
0       A   Agra
1       B    NaN
2       C    NaN
3       D  Delhi

### 15. Read a copied spreadsheet/webpage table using the clipboard method.

In [16]:
# First copy a table (including its headers) from a spreadsheet or webpage.
# Then run this cell.
copied_df = pd.read_clipboard()
copied_df

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

## Section B — Moderate (10 Questions)

### 16. Create `employee_df` with five rows and display Employee and Experience.

In [ ]:
employee_df = pd.DataFrame({
    'Employee': ['Aman', 'Riya', 'Dev', 'Meera', 'Arjun'],
    'Department': ['IT', 'HR', 'Sales', 'IT', 'Finance'],
    'Experience': [2, 4, 1, 3, 5]
})
employee_short = employee_df[['Employee', 'Experience']]
employee_short

### 17. Retrieve Department and display all column names.

In [ ]:
employee_df['Department']

### 17 (continued). Display all column names.

In [ ]:
employee_df.columns

### 18. Add Office = 'Head Office' to every row and display the updated DataFrame.

In [ ]:
employee_df['Office'] = 'Head Office'
employee_df

### 19. Replace Office values with `np.arange(5)`.

In [ ]:
employee_df['Office'] = np.arange(5)
employee_df

### 20. Assign a partially indexed Series to Office.

In [ ]:
office_names = pd.Series(['Delhi', 'Mumbai', 'Pune'], index=[0, 2, 4])
employee_df['Office'] = office_names
employee_df

### 21. Delete Office and display the remaining columns.

In [ ]:
del employee_df['Office']
employee_df

### 22. Create `product_df`, then reorder columns as Price, Product, Category.

In [ ]:
product_df = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Keyboard'],
    'Category': ['Electronics', 'Accessory', 'Accessory'],
    'Price': [55000, 700, 1500]
})
product_reordered = product_df[['Price', 'Product', 'Category']]
product_reordered

### 23. Request four columns when one is missing from the source data.

In [ ]:
source_df = pd.DataFrame({
    'Name': ['Asha', 'Rahul', 'Zoya'],
    'Age': [19, 20, 18],
    'City': ['Agra', 'Delhi', 'Noida']
})
requested_df = source_df.reindex(columns=['Name', 'Age', 'City', 'Course'])
requested_df
# The missing Course column is filled with NaN values.

### 24. Retrieve a column whose name contains a space.

In [ ]:
marks_df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Dev'],
    'Total Marks': [85, 92, 78]
})
marks_df['Total Marks']

### 25. Read a copied table, show its columns, and select any three columns.

In [ ]:
# Copy a table with at least three columns before running this cell.
copied_df = pd.read_clipboard()
display(copied_df.columns)
selected_copied_df = copied_df.iloc[:, :3]
selected_copied_df

## Section C — Hard (5 Questions)

### 26. Create `course_df`; display columns, retrieve Student, select Student and Score, and add Batch.

In [ ]:
course_df = pd.DataFrame({
    'Student': ['Aman', 'Riya', 'Dev', 'Meera', 'Arjun'],
    'Course': ['Python', 'Java', 'Pandas', 'SQL', 'Python'],
    'Score': [88, 91, 79, 85, 94]
})
display(course_df.columns)
display(course_df['Student'])
course_student_score = course_df[['Student', 'Score']]
display(course_student_score)
course_df['Batch'] = '2026'
course_df

### 27. Create `travel_df`, add Code with `np.arange(5)`, then replace it with a partially indexed Series.

In [ ]:
travel_df = pd.DataFrame({
    'Destination': ['Agra', 'Delhi', 'Jaipur', 'Lucknow', 'Mumbai'],
    'Days': [1, 2, 3, 2, 4]
})
travel_df['Code'] = np.arange(5)
display(travel_df)

travel_codes = pd.Series([101, 404], index=[1, 4])
travel_df['Code'] = travel_codes
display(travel_df)

### 28. Request a missing House column, then assign one common value to it.

In [ ]:
school_df = pd.DataFrame({
    'Student': ['Aman', 'Riya', 'Dev', 'Meera'],
    'Class': [11, 12, 11, 12],
    'Section': ['A', 'B', 'A', 'C']
})
school_extended = school_df.reindex(columns=['Student', 'Class', 'Section', 'House'])
display(school_extended)

school_extended['House'] = 'Blue House'
school_extended

### 29. Add a column using a partially indexed Series, display it, delete it, and display again.

In [ ]:
inventory_df = pd.DataFrame({
    'Item': ['Pen', 'Notebook', 'Pencil', 'Eraser'],
    'Quantity': [20, 15, 30, 12]
})
stock_series = pd.Series([100, 200], index=[0, 2])
inventory_df['StockCode'] = stock_series
display(inventory_df)

del inventory_df['StockCode']
display(inventory_df)

### 30. Clipboard workflow: display table, columns, select columns, add a column, then delete it.

In [ ]:
# Copy a table with at least four columns (including headers) before running this cell.
lab_df = pd.read_clipboard()

display(lab_df)
display(lab_df.columns)

# Retrieve a single-word column: replace 'Name' if your copied table uses another heading.
# Retrieve a column containing a space: replace 'Total Marks' if needed.
# The try/except blocks help the cell run even if your table has different headings.
if 'Name' in lab_df.columns:
    display(lab_df['Name'])
else:
    display(lab_df.iloc[:, 0])

space_columns = [col for col in lab_df.columns if ' ' in str(col)]
if space_columns:
    display(lab_df[space_columns[0]])
else:
    print('No column with a space in its name was found.')

selected_columns = list(lab_df.columns[:3])
small_lab_df = lab_df[selected_columns]
display(small_lab_df)

lab_df['NewColumn'] = 'Practice'
display(lab_df)

del lab_df['NewColumn']
display(lab_df)